### ISSUE TITLE
Feature-Booster ORB_SLAM2

### ISSUE THREAD

**Issue by ZengQiHua** [SJTU-ViSYS/FeatureBooster#8]
大佬好，我把pytorch模型转为onnx，再转成trt模型，部署在ORBSLAM3中。我只对初始化成功后的描述子进行增强，但是出现VO跟踪失败，所以请问您将ORB特征点描述子增强模型部署在ORBSLAM2中，SLAM系统初始化的描述子也增强了吗？你们也是转成trt用C++部署吗？

**Comment by Antu3heng** [comment]
Yes, you should boost the ORBs of the entire ORB-SLAM system. If you only boost the ORB in tracking, the map created by the initialization will not be able to be tracked, since the feature in this map is using the ORB without a boost and the ORB and ORB+Boost-B could be seen as two different descriptors. Besides, we use the LibTorch rather than TensorRT.

**Comment by Antu3heng** [comment]
Closed due to no longer being active. Can be reopened at any time.

**Comment by qinqi-mm** [comment]
> 大佬好，我把pytorch模型转为onnx，再转成trt模型，部署在ORBSLAM3中。我只对初始化成功后的描述子进行增强，但是出现VO跟踪失败，所以请问您将ORB特征点描述子增强模型部署在ORBSLAM2中，SLAM系统初始化的描述子也增强了吗？你们也是转成trt用C++部署吗？

您好，冒昧地请问您一下，您成功将这个算法应用到ORBSLAM3里了嘛？
